name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docs_path: docs/build/html
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autodoc-typehints
          pip install -r requirements.txt
      - run: sphinx-apidoc -o docs/source/ hexrec
      - run: rm -rf docs/build
      - run: cd docs && make html
      - uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
